### ISSUE TITLE
Unable to create RSA-4096 key

### ISSUE THREAD

**Issue by youk** [unreality/nCryptAgent#10]
Getting the following message when trying to create a RSA-4096 key:
```
unable to set key NCRYPT_LENGTH_PROPERTY:
NCryptSetProperty "Length" returned NTE_INVALID_PARAMETER:
The operation completed succesfully
```
The log file has no related info.

Windows 10 Pro 22H2

**Comment by unreality** [comment]
nCryptAgent always attempts to use the TPM, and most TPM chips (or fTPM) only support RSA 2048.

I'll merge this into another issue for generating a better error, or interrogating the TPM to find out what algorithms/lengths are available.
