### ISSUE TITLE
Unable to use wsl2 agent socket

### ISSUE THREAD

**Issue by tommy2d** [unreality/nCryptAgent#3]
I previously used the native OpenSSH agent in windows 11 which was forwarded to WSL2, which worked. I'm now trying your solution, and thus I disabled the SSH agent service in windows. Native ssh through powershell is working fine. I can't seem to get WSL2 to work, even though the env vars seem to be alright and the socket is created in /tmp. 

ssh-add -L yields the following the error:

error fetching identities: communication with agent failed

How should I debug this?

**Comment by unreality** [comment]
@tommy2d can you check that `socat` is installed in your WSL2 VM? The script will silently fail if its not installed, so check that first...

**Comment by farcaller** [comment]
Same issue here and I do have socat installed (and it is in fact running after executing the snippet).

**Comment by unreality** [comment]
I'll see if i can reproduce this with a Win11 VM, and i'll put out a new version later today which will output logs into the appdata directory to help debug this...

**Comment by tommy2d** [comment]
Same here: socat is in fact installed & running and was also used by my previous wsl2 solution. I'll try your updated version later today.

**Comment by unreality** [comment]
Here is the workaround until I add some checks and an installer:

Create `ncrypt.reg` with the following content:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\GuestCommunicationServices\22223333-facb-11e6-bd58-64006a7986d3]
"ElementName"="nCryptAgent"
```

and install it. Alternatively create the registry entry by hand.

**Comment by farcaller** [comment]
Ha, I thought that was it based on the [docs](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/make-integration-service). The registry entry does indeed work as expected.

**Comment by tommy2d** [comment]
I'm afraid it is still not working for me, even after importing the .reg. Is there anything else I can do to help?

**Comment by tommy2d** [comment]
Fixed it: my default wsl2 VM was apparently running an older version of Ubuntu, bundled with an older version of socat:

Working:
bookworm/sid
Version: 1.7.4.1-3ubuntu4

Not working
bullseye/sid
Version: 1.7.3.3-2

We should probably update the shell scripts to verify that socat is compatible.
