### ISSUE TITLE
Unable to use the tpm / yubikey

### ISSUE THREAD

**Issue by farcaller** [unreality/nCryptAgent#5]
The load existing key option doesn't work for me:
![image](https://user-images.githubusercontent.com/693/200850346-9a98d6c8-153f-43e4-bf11-136c0584c3dc.png)

I suspect the container should be non-empty following a call to `ListKeysOnProvider`, but here we are. The list is never populated neither on the TPM based virtual card not on a YubiKey.

**Comment by farcaller** [comment]
Nope.

**Comment by unreality** [comment]
If `certutil -key -user -csp SC` doesnt list any keys, it means there are none that nCrypt knows about on the system. I have seen it fail to find ones on Yubikeys, but it usually always lists the ones on virtual smart cards. 

You could try running `certutil -scinfo` to list all the certificates and keys that windows knows about. Depending on how many x509 certificates you have loaded onto your smart cards, it should list out a few entries looking like:

```
================ Certificate 0 ================
--- Reader: Microsoft Virtual Smart Card 0
---   Card: Identity Device (Microsoft Generic Profile)
Provider = Microsoft Smart Card Key Storage Provider
Key Container = XXXXXXXXX
```

If it lists none, have you confirmed that your smart cards have certificates on them?

**Comment by farcaller** [comment]
It looks like the tpm got the cert, but not the yubikey:

```
=======================================================
Analyzing card in reader: Microsoft Virtual Smart Card 0
AIK KeyId(sha1): 49505a02d0039dd98597ede54d3942d74586b09e
AIK KeyId(sha256): 3e37613c2546bab14612d0cffb0b01ac19de86163f1d36bda75d9fd1511cb8a6
Serial Number: 41e8cfb625d042f3af9f34501c705b35
Issuer: CN=EUS-NTC-KEYID-23F4E22AD3BE374A449772954AA283AED752572E
 NotBefore: 08/11/2022 13:59
 NotAfter: 03/06/2027 17:51
Subject: EMPTY (Directory Address:TPMModel=NPCT75x + TPMManufacturer=id:4E544300 + TPMVersion=id:00070002)
Non-root Certificate
Cert Hash(sha1): d78ae4ff8f32795a224b1549b5f2017d4f038821
Microsoft Base Smart Card Crypto Provider: Missing stored keyset
AIK KeyId(sha1): 49505a02d0039dd98597ede54d3942d74586b09e
AIK KeyId(sha256): 3e37613c2546bab14612d0cffb0b01ac19de86163f1d36bda75d9fd1511cb8a6
Serial Number: 41e8cfb625d042f3af9f34501c705b35
Issuer: CN=EUS-NTC-KEYID-23F4E22AD3BE374A449772954AA283AED752572E
 NotBefore: 08/11/2022 13:59
 NotAfter: 03/06/2027 17:51
Subject: EMPTY (Directory Address:TPMModel=NPCT75x + TPMManufacturer=id:4E544300 + TPMVersion=id:00070002)
Non-root Certificate
Cert Hash(sha1): d78ae4ff8f32795a224b1549b5f2017d4f038821
Microsoft Smart Card Key Storage Provider: Missing stored keyset

--------------===========================--------------

=======================================================
Analyzing card in reader: Yubico YubiKey OTP+FIDO+CCID 0
Microsoft Base Smart Card Crypto Provider: Missing stored keyset
Microsoft Smart Card Key Storage Provider: Missing stored keyset

--------------===========================--------------
CertUtil: -SCInfo command FAILED: 0x80090016 (-2146893802 NTE_BAD_KEYSET)
CertUtil: Keyset does not exist
```

despite YK showing PIV with all 4 certs:
![image](https://user-images.githubusercontent.com/693/201096447-c6b1bfeb-dad5-4d55-a282-d9f9c73a2a31.png)

**Comment by unreality** [comment]
Thats super interesting, ive not seen that before. I'm presuming the certificates on the Yubikey were provisioned and installed using `ykman` or the Yubikey Manager App, and not via `certreq` and `certutil` on windows?

That TPM cert its showing looks like the attestation certificate, and not a cert on the card though.

A long-shot may be to re-insert the Yubikey which triggers the certificate propagation service to load all the certificates again. You can check that this is occurring by running `certmgr.msc` and confirming the certificates appear in the Personal store, if they arent there that could also be the problem (check that smart card services are running and the [certificate propagation service
](https://learn.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-propagation-service) is running)

**Comment by farcaller** [comment]
I did some [troubleshooting](https://support.yubico.com/hc/en-us/articles/360013780779-Troubleshooting-No-Valid-Certificates-Were-Found-on-This-Smart-Card-) and figured I was lacking a YubiKey Smart Card Minidriver. FFS. At least the issue is solved!

**Comment by farcaller** [comment]
Oh and – the other issue was my using ECC keys. It seems that it only works with RSA.
