### ISSUE TITLE
key not recognized on inserting after startup 

### ISSUE THREAD

**Issue by alexstaal** [unreality/nCryptAgent#7]
When inserting a yubi key after ncryptAgent is already started, the key isn't recognized. After exiting and restarting ncryptAgent (with the key still inserted), the key is recognized.

**Comment by unreality** [comment]
Do you mean when you use 'Add Existing Key' or the UI shows the key as 'missing'?

nCryptAgent should prompt you to insert your Yubikey via the 'Select Smart Card' UI that pops up when you attempt to login to something that uses that ssh key, even if the UI says it is missing.

**Comment by alexstaal** [comment]
When starting without the key, the status indeed is 'missing'. When starting something that uses the ssh key, there is no prompt for inserting the yubi key, it also closes the gui. 
When status=missing, insert the yubi key, same issue. 

If i exit the agent and start it with a yubi key already inserted, status=available and no problems. When removing the key at this point, status remains available. When starting something that uses the key , indeed a prompt to insert the key and no further issues

**Comment by unreality** [comment]
I'll try find some time to add a listener for USB insert/remove events to update the keys when Yubikeys are added/removed

**Comment by unreality** [comment]
@alexstaal please try out the latest release v0.0.6 and let me know if it has fixed the issue for you
